### ISSUE TITLE
fix (a11y): Colour-blind friendly mechanism to distinguish between issue and PR states

### ISSUE THREAD

**Issue by nikclayton** [nathonius/obsidian-github-link#68] opened 2024-02-27 10:03 UTC
At the moment an issue chip renders with a leading "dot in a square", coloured either green if the issue is open or red if the issue is closed.

This is problematic for a couple of reasons.

1. The colour scheme feels backwards (for some cultures) -- an open issue indicates a problem (bad), a closed issue indicates a problem has been resolved (good)
2. The red/green are not differentiable under some forms of colour blindness.

I've attached a file that demonstrates this. If you save this file, and then load it in to the simulator at https://www.color-blindness.com/coblis-color-blindness-simulator/ you'll see that for some people the colours are either very close or indistinguishable.

I'd recommend removing the use of red/green entirely to communicate the state, and use different icons to clearly distinguish between them.

Thanks.

Edit to add: PRs have a similar issue; the state of the PR (unmerged or merged) is communicated solely through colour, the icons for unmerged and merged are the same.

---

![colour-blind-demo](https://github.com/nathonius/obsidian-github-link/assets/773100/bef7ceb7-3084-4099-a77f-f96b2e21756e)

**Comment by nathonius** [comment] 2024-02-27 17:08
@nikclayton thanks for bringing this up! So for this I'm using the primer library, which is the CSS library github uses for colors: https://github.com/primer/css

It looks like I might have some mismatch on determining when to use which color. Open issues should be green, closed should be purple. This is the convention that github uses. I'll also see if I can find a good closed issue icon; github replaces the dot with a checkmark once the issue is closed.

**Comment by nikclayton** [comment] 2024-02-28 23:17
> Open issues should be green, closed should be purple

FWIW I see open PRs are green and merged PRs are purple. However, again, their state (open or merged) is only communicated through the colour of the icon, there's no colour-blind friendly alternative indication of the state.

**Comment by nikclayton** [comment] 2024-02-29 08:46
Just noticed that the GitHub Android app uses different icons to distinguish between merged (top) and unmerged PRs, whereas the plugin just uses the bottom icon.

![Screenshot_20240229-094412.png](https://github.com/nathonius/obsidian-github-link/assets/773100/6e3864ca-c495-46a7-a75f-3b48b90b47b4)

**Comment by nathonius** [comment] 2024-02-29 22:11
Aha, perhaps this is a different issue then - I'm also using the pull request icons, the single dots are for issues. Perhaps it's not detecting that correctly. Can you share a couple of the links you're using? Or links that show the same behavior.

**Comment by nikclayton** [comment] 2024-03-01 10:26
Sure (I've updated this issue's title/body to cover PRs as well as issues as well).

At the time I've writing, if I open an Obsidian file and paste in

```
https://github.com/pachli/pachli-android/pull/473
https://github.com/pachli/pachli-android/pull/480
```

it renders as the following screenshot:

![image](https://github.com/nathonius/obsidian-github-link/assets/773100/e33834c6-e126-4816-910f-6bc1e0947892)

Of those, the first PR is **unmerged**, the second is **merged**. As you can see, they render with identical icons, just the colour is different.

The screenshot from the GitHub app that I included in https://github.com/nathonius/obsidian-github-link/issues/68#issuecomment-1970672178 shows what I think is the correct icon to use for merged PRs.

In the specific case of pull requests I think you might only be checking whether or not the PR is closed. You might also need to make an explicit check to see if it's been merged (https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#check-if-a-pull-request-has-been-merged) to show the correct icon.

So for PRs arguably this is at least a tri-state, and the icon + colours could indicate:

- PR is open
- PR is closed (and not merged)
- PR is closed (and merged)

That could be extended further to indicate:

- PR is open and mergeable (all reviews approve, no checks that are blocking the merge)
- PR is open and not mergeable

Completely understand if that last one makes sense as a separate feature request.

**Comment by nathonius** [comment] 2024-03-09 22:17
Okay, so it seems like there's a number of separate issues here:
- Closed as completed issues should be purple in color, not red
- Icons should more clearly communicate the status of an issue or PR

Thirdly, there's a couple feature requests here:
- Show mergibility of PRs
- Better a11y in general

I'm going to spin this off into a few extra issues to split it up.

**Closed by nathonius** 2024-03-09 22:17 UTC
Labels: bug

**Comment by nathonius** [comment] 2024-04-12 03:05
Simple mergeable / not mergeable PR status checks have been added.
